### ISSUE TITLE
Fails if there's no config in ~/.kube

### ISSUE THREAD

**Issue by tarekmehrez** [jonmosco/kube-ps1#32]
I have 3 different contexts, all set in KUBECONFIG.
kube-prompt fails when I try to get a certain pod or service

```bash
>>> get pods panic: stat /Users/tarekmehrez/.kube/config: no such file or directory

goroutine 36 [running]:
github.com/c-bata/kube-prompt/kube.NewClient(0x0)
	/Users/a14737/go/src/github.com/c-bata/kube-prompt/kube/client.go:29 +0x140
github.com/c-bata/kube-prompt/kube.getClient(0x0)
	/Users/a14737/go/src/github.com/c-bata/kube-prompt/kube/client.go:14 +0x2e
github.com/c-bata/kube-prompt/kube.fetchPods()
	/Users/a14737/go/src/github.com/c-bata/kube-prompt/kube/resource.go:177 +0x72
created by github.com/c-bata/kube-prompt/kube.getPodSuggestions
	/Users/a14737/go/src/github.com/c-bata/kube-prompt/kube/resource.go:183 +0x39
```

Is there a way that this might work just by checking my current context?

**Comment by jonmosco** [comment]
kube-prompt ?   Is this for kube-ps1?  Looks like that error is not related to this project.

**Comment by tarekmehrez** [comment]
ohh wrong repo, my bad :)

**Comment by jonmosco** [comment]
No problem.
